keywords: "ScottDover, technology, programming, winston salem, nc, php, ruby, theology"
description: "A blog on programming, technology, theology and every topic that strikes my interest"

name: "ScottDover"
markdown: redcarpet
pygments: true

#relative_permalinks: false
permalink: none

#url: "http://scottdover.github.io/"
baseurl: "/"
paginate: 2
paginate_path: "blog/page:num"